### ISSUE TITLE
lot of .bind(this) which seems 'strange' at first

### ISSUE THREAD

**Issue by jeromeetienne** [cubicleDowns/ng-three-viewer#2]
Hello, 

im following your talk and trying to understand the source. lot of things to learn, thanks!

i know three.js pretty well, but very little about angularjs. and i keep find functions like that. It seems 'strange' to me. care to explain ?

```
this.force = this.force.bind(this);
```

from https://github.com/cubicleDowns/ng-three-viewer/blob/master/v2/src/js/ng/filters.js#L8 but present in many places in the source

Thanks

**Comment by cubicleDowns** [comment]
The "this" you're referring to is typically the local scope of the constructed filter.  In this snippet, we are associating the call for this.force with the prototype. Filters are using a factory to self-construct which makes this all kind of confusing given how frequently they could be used.

Here is a link an example of a [factory pattern](https://carldanley.com/js-factory-pattern/) though a little different.
